// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bar: typeof import('./src/components/bar.vue')['default']
    Card: typeof import('./src/components/card.vue')['default']
    Comment: typeof import('./src/components/comment.vue')['default']
    DetailsComponent: typeof import('./src/components/detailsComponent.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    Popup: typeof import('./src/components/popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./src/components/scroll.vue')['default']
    ScrollText: typeof import('./src/components/scrollText.vue')['default']
    SongTable: typeof import('./src/components/songTable.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCircle: typeof import('vant/es')['Circle']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPasswordInput: typeof import('vant/es')['PasswordInput']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSlider: typeof import('vant/es')['Slider']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
